sudo: false
language: ruby
# without --debug, JRuby doesn't support coverage reporting
before_install:
  - gem install bundler
env:
  - JRUBY_OPTS="--debug"
rvm:
  - 2.2
  - 2.3.1
  - jruby-head
#  - ruby-head  # Failure unrelated to quality gem - see https://travis-ci.org/apiology/quality/jobs/131303133
