sudo: false
language: ruby
# without --debug, JRuby doesn't support coverage reporting
before_install:
  - gem install bundler
env:
  - JRUBY_OPTS="--debug"
rvm:
  - 2.2.2
  - 2.3.1
  - 2.4.0
#  - jruby-head # linguist gem doesn't support JRuby; bundle install doesn't work.
  - ruby-head
